baseURL = 'https://dev-undergrad.dev/'
languageCode = 'en-us'
title = 'Undergraduate Notes'
theme = 'HugoTeX'
paginate = 4
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[author]
  name = "Deval Deliwala"
  abstract = "I study  astrophysics & math @ UC Berkeley. My primary interests lie in quantum computing. Here I compile all my notes from all my lectures & elsewhere. "

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"

[Params]
  darkmode = true




